# Generated by Django 3.0.5 on 2020-05-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumb',
            field=models.ImageField(blank=True, default='cat.jpg', upload_to=''),
        ),
    ]
